name: Update GitHub contributions JSON

on:
  schedule:
    - cron: '0 0 * * *' # 00:00 UTC daily = 08:00 SGT
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate contributions JSON
        run: |
          node -e "const https=require('https');
          const query=JSON.stringify({query: 'query { user(login: \"gongahkia\") { contributionsCollection { contributionCalendar { totalContributions weeks { contributionDays { date contributionCount } } } } } }'});
          const req=https.request({hostname:'api.github.com',path:'/graphql',method:'POST',headers:{'User-Agent':'actions','Content-Type':'application/json','Authorization':'Bearer '+process.env.GITHUB_TOKEN}},res=>{let d='';res.on('data',c=>d+=c);res.on('end',()=>{try{const js=JSON.parse(d); console.log('API Response:', JSON.stringify(js, null, 2)); if(js.errors){console.error('GraphQL Errors:', js.errors); process.exit(1);} if(!js.data||!js.data.user){console.error('No user data found:', js); process.exit(1);} const weeks=js.data.user.contributionsCollection.contributionCalendar.weeks.map(w=>({days:w.contributionDays.map(cd=>({date:cd.date,count:cd.contributionCount}))})); const max=Math.max(0,...weeks.flatMap(w=>w.days.map(x=>x.count))); const out={weeks,max}; require('fs').mkdirSync('asset',{recursive:true}); require('fs').writeFileSync('asset/contributions.json', JSON.stringify(out)); console.log('Successfully generated contributions.json');}catch(e){console.error('Error processing response:', e); console.error('Raw response:', d); process.exit(1);}});}); req.on('error',e=>{console.error(e); process.exit(1);}); req.write(query); req.end();"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit changes
        run: |
          if [[ -n $(git status --porcelain) ]]; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add asset/contributions.json
            git commit -m "chore: update contributions.json"
            git push
          fi

